### ISSUE TITLE
I can't see the play menu/bar and subtitle options

### ISSUE THREAD

**Issue by ghost** [Cuevana/storm#27]
I can perfectly watch the movie, but isn't it supposed to see the "status bar/play bar/subtitles option bar" down on the window?

**Comment by ivantodorovich** [comment]
I see it fine here. Did the console throw any errors?

**Comment by locotobi** [comment]
I have the same error... It happens to me with the original popcorntime.- This was a common error for windows 8... It was fixed with a simply change in 2 consecutives lines of a file but I dont remember what file or what lines... I do remember that it was something related with the posibility of Touchscreen by default on windows 8.... I hope you fix this soon.-
Regards.-

Windows 8 64-bits

**Comment by fluzzi** [comment]
I have the same issue also in windows 8 32 and 64 bits, also when on using touch screen the bar apears so it seems an issue with no-touch screens on win8
